# Generated by Django 5.1 on 2025-01-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
