# Generated by Django 5.1 on 2025-01-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
